# Generated by Django 4.2.7 on 2023-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=250)),
                ('tanasi', models.TextField()),
                ('vaqt', models.DateTimeField()),
                ('rasm', models.ImageField(upload_to='blog_rasmlari/')),
            ],
        ),
    ]
