# Generated by Django 4.2.7 on 2023-12-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_rasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='avtor',
        ),
    ]
