# Generated by Django 4.2.7 on 2023-12-29 11:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_remove_blog_avtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 16, 21, 59, 941994), help_text='Maqolaning vaqti'),
        ),
    ]
